###################################################
#Author: Almir Candido                            #
#Contact: https://br.linkedin.com/in/almircandido #
#                                                 #
#Ansible Version: 2.9                             #
#                                                 #
#Requisitos:                                      #
#Install:                                         #
#python-boto                                      #
#python-boto3                                     #
#pip install boto3                                #
###################################################
#Documentation about module
#https://docs.ansible.com/ansible/latest/modules/iam_password_policy_module.html
# AWS manage password policy
---
- hosts: localhost
  gather_facts: no
  vars:
    AWS_ACCESS_KEY: xxxxxxxxxxxxxxxxxxxx #inform access key
    AWS_SECRET_KEY: xxxxxxxxxxxxxxxxx #inform secret key
    PASSWORD_LENGTH: 8
    PASSWORD_EXPIRATION: 60
    PASSWORD_REUSE_PREVENT: 4
  tasks:
    - name: AWS Manage Password Policy
      iam_password_policy:
        aws_access_key: "{{ AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        min_pw_length: "{{ PASSWORD_LENGTH }}"
        require_symbols: true
        require_numbers: true
        require_uppercase: true
        require_lowercase: true
        allow_pw_change: true
        pw_max_age: "{{ PASSWORD_EXPIRATION }}"
        pw_reuse_prevent: "{{ PASSWORD_REUSE_PREVENT }}"
        pw_expire: true
        state: present
...
