###################################################
#Author: Almir Candido                            #
#Contact: https://br.linkedin.com/in/almircandido #
#                                                 #
#Ansible Version: 2.9                             #
#                                                 #
#Requisitos:                                      #
#Install:                                         #
#python-boto                                      #
#python-boto3                                     #
#pip install boto3                                #
###################################################
#Documentation about modules
#https://docs.ansible.com/ansible/latest/modules/ec2_instance_info_module.html
#https://docs.ansible.com/ansible/latest/modules/ec2_ami_module.html
#https://docs.ansible.com/ansible/latest/modules/ec2_module.html
#AWS Create an instance image and create a new instance with that image.
#
---
- hosts: localhost
  gather_facts: no
  vars:
    AWS_ACCESS_KEY: xxxxxxxxxxxxxxxxxxxx #inform access key
    AWS_SECRET_KEY: xxxxxxxxxxxxxxxxxxxx #inform secret key
    AWS_REGION: us-east-1 # N. Virginia
    TAG_NAME: webserver01
    IMAGE_NAME: new_webserver01
    KEY_NAME: almir_ssh
    INSTANCE_TYPE: t2.micro
    INSTANCE_TAG: webserver02
    SECURITY_GROUP_NAME: almir_ssh
  tasks:
    - name: Instance Facts
      ec2_instance_info:
        aws_access_key: "{{ AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        region: "{{ AWS_REGION }}"
        filters:
          "tag:Name": "{{ TAG_NAME }}"
      register: result
      
#
    - name: Create Image
      ec2_ami:
        aws_access_key: "{{ AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        region: "{{ AWS_REGION }}"
        instance_id: "{{ item.instance_id }}"
        name: "{{ IMAGE_NAME }}"
        wait: yes
        tags:
          Name: "{{ IMAGE_NAME }}"
      loop: "{{ result.instances }}"
      register: new_ami
#
    - name: Create new instance from ami
      ec2:
        aws_access_key: "{{ AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        region: "{{ AWS_REGION }}"
        key_name: "{{ KEY_NAME }}"
        instance_type: "{{ INSTANCE_TYPE }}"
        group: "{{ SECURITY_GROUP_NAME }}"
        image: "{{ item.image_id }}"
        wait: yes
        instance_tags:
          Name: "{{ INSTANCE_TAG }}"
      loop: "{{ new_ami.results }}"
...
